# Generated by Django 3.0.5 on 2020-04-09 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coordinator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Укажите учетную запись пользователя', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Учетная запись'),
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, help_text='Дата регистрации вызова', verbose_name='Дата вызова')),
                ('address', models.CharField(help_text='Адрес вызова', max_length=200, verbose_name='Адрес')),
                ('record_order', models.IntegerField(help_text='Порядковый номер вызова', verbose_name='Порядок')),
                ('doctor', models.ForeignKey(blank=True, help_text='Врач назначенный на вызов', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_records', to='coordinator.Doctor', verbose_name='Врач')),
            ],
            options={
                'verbose_name': 'Вызов',
                'verbose_name_plural': 'Вызовы',
            },
        ),
    ]
