# Generated by Django 3.0.5 on 2020-04-15 17:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0003_auto_20200415_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Адрес вызова', max_length=200, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Вид обслуживания',
                'verbose_name_plural': 'Виды обслуживания',
            },
        ),
        migrations.RemoveField(
            model_name='record',
            name='date_deprecated',
        ),
        migrations.AddField(
            model_name='doctor',
            name='temperature',
            field=models.BooleanField(default=False, help_text='Обслуживает температурные вызовы', verbose_name='Температура'),
        ),
        #migrations.AddField(
        #    model_name='record',
        #    name='finish_date',
        #    field=models.DateTimeField(blank=True, help_text='Дата/время завершения вызова', null=True, verbose_name='Завершен'),
        #),
        migrations.AddField(
            model_name='record',
            name='patient',
            field=models.CharField(default='', help_text='Фамилия И.О.', max_length=150, verbose_name='Пациент'),
        ),
        migrations.AddField(
            model_name='record',
            name='patient_birthdate',
            field=models.DateField(default='1900-01-01', help_text='Дата рождения пациента', verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='record',
            name='send_date',
            field=models.DateTimeField(blank=True, help_text='Дата/время передачи вызова', null=True, verbose_name='Передан'),
        ),
        migrations.AddField(
            model_name='record',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Дата регистрации вызова', verbose_name='Поступил'),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_order',
            field=models.IntegerField(default=0, help_text='Порядковый номер вызова', verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='record',
            name='service_type',
            field=models.ForeignKey(blank=True, help_text='Как был обслужен вызов', null=True, on_delete=django.db.models.deletion.CASCADE, to='coordinator.ServiceType', verbose_name='Вид обслуживания'),
        ),
    ]
