# Generated by Django 3.0.5 on 2020-04-15 10:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0002_auto_20200409_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='date',
            new_name='date_deprecated',
        ),
        migrations.AddField(
            model_name='record',
            name='finish_date',
            field=models.DateTimeField(blank=True, help_text='Дата/время завершения вызова', null=True, verbose_name='Завершен'),
        ),
        migrations.AddField(
            model_name='record',
            name='send_date',
            field=models.DateTimeField(blank=True, help_text='Дата/время передачи вызова', null=True, verbose_name='Передан'),
        ),
        migrations.AddField(
            model_name='record',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Дата регистрации вызова', verbose_name='Поступил'),
        ),
    ]
