# Generated by Django 3.0.5 on 2020-04-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0003_auto_20200415_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='temperature',
            field=models.BooleanField(default=False, help_text='Температурный вызов', verbose_name='Температура'),
        ),
    ]
