# Generated by Django 3.0.5 on 2020-04-17 09:22

#from __future__ import unicode_literals
from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    ServiceType = apps.get_model("coordinator", "ServiceType")
    db_alias = schema_editor.connection.alias
    ServiceType.objects.using(db_alias).bulk_create([
        ServiceType(id=1, name="Температурный"),
        ServiceType(id=2, name="Лично"),
        ServiceType(id=3, name="По телефону"),
    ])

def reverse_func(apps, schema_editor):
    # forwards_func() creates some instances,
    # so reverse_func() should delete them.
    ServiceType = apps.get_model("coordinator", "ServiceType")
    db_alias = schema_editor.connection.alias
    ServiceType.objects.using(db_alias).filter(id=1).delete()
    ServiceType.objects.using(db_alias).filter(id=2).delete()
    ServiceType.objects.using(db_alias).filter(id=3).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0005_department'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
