# Generated by Django 3.0.5 on 2020-04-19 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0010_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AddField(
            model_name='record',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Подразделение', null=True, on_delete=django.db.models.deletion.SET_NULL, to='coordinator.Department', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='record',
            name='doctor',
            field=models.ForeignKey(blank=True, help_text='Врач назначенный на вызов', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_records', to='coordinator.Doctor', verbose_name='Врач'),
        ),
    ]
