# Generated by Django 3.0.5 on 2020-04-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0011_record_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='address',
            field=models.CharField(blank=True, default='', help_text='Адрес вызова', max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='record',
            name='address_apartment',
            field=models.CharField(blank=True, default='', help_text='Квартира', max_length=10, verbose_name='Квартира'),
        ),
    ]
