# Generated by Django 3.0.5 on 2020-04-25 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0012_record_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={
                # 'permissions': [('can_view_own', 'Can view own')],
                'verbose_name': 'Вызов',
                'verbose_name_plural': 'Вызовы'
            },
        ),
        migrations.AlterField(
            model_name='record',
            name='doctor',
            field=models.ForeignKey(
                blank=True,
                help_text='Врач назначенный на вызов',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='coordinator.Doctor',
                verbose_name='Врач',
            ),
        ),
    ]
