# Generated by Django 3.0.5 on 2020-04-25 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0013_record_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'permissions': [('view_own', 'Can view own record')], 'verbose_name': 'Вызов', 'verbose_name_plural': 'Вызовы'},
        ),
    ]
