# Generated by Django 3.0.5 on 2020-04-28 10:07

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    ServiceType = apps.get_model("coordinator", "ServiceType")
    db_alias = schema_editor.connection.alias
    ServiceType.objects.using(db_alias).bulk_create([
        ServiceType(id=5, name="Не пустили"),
    ])
    Group = apps.get_model("auth", "group")
    db_alias = schema_editor.connection.alias
    Group.objects.using(db_alias).bulk_create([
        Group(id=1, name="Координаторы"),
        Group(id=2, name="Врачи"),
    ])


def reverse_func(apps, schema_editor):
    # forwards_func() creates some instances,
    # so reverse_func() should delete them.
    ServiceType = apps.get_model("coordinator", "ServiceType")
    db_alias = schema_editor.connection.alias
    ServiceType.objects.using(db_alias).filter(id=5).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0014_auto_20200425_1527'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
