# Generated by Django 3.0.5 on 2020-04-29 14:22

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Group = apps.get_model("auth", "group")
    db_alias = schema_editor.connection.alias
    Group.objects.using(db_alias).bulk_create([
        Group(id=3, name="Руководители"),
        Group(id=4, name="Только просмотр"),
    ])


def reverse_func(apps, schema_editor):
    # forwards_func() creates some instances,
    # so reverse_func() should delete them.
    Group = apps.get_model("auth", "group")
    db_alias = schema_editor.connection.alias
    Group.objects.using(db_alias).filter(id=3).delete()
    Group.objects.using(db_alias).filter(id=4).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0015_service_type_didnt_let'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
