# Generated by Django 3.0.5 on 2020-05-06 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateTimeField(auto_now=True, verbose_name='Дата/время')),
                ('model', models.CharField(help_text='Имя сущности', max_length=255, null=True, verbose_name='Данные')),
                ('record', models.IntegerField(help_text='Идентификатор записи', null=True, verbose_name='Запись')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление')], help_text='Действие', max_length=50, null=True, verbose_name='Действие')),
                ('action_data', models.TextField(help_text='Изменяемые данные', verbose_name='Изменяемые данные')),
                ('user', models.ForeignKey(help_text='Пользователь, выполнивший действие', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись журнала изменений',
                'verbose_name_plural': 'Записи журнала изменений',
                'ordering': ('action_date',),
            },
        ),
    ]
